# Generated by Django 5.2.8 on 2025-11-18 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ジャンル名')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店舗名')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('spec', models.TextField(blank=True, verbose_name='基本仕様')),
                ('price', models.IntegerField(default=0, verbose_name='単価')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品写真')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.genre', verbose_name='ジャンル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='顧客')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.store', verbose_name='店舗')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='注文日時')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='希望納品日')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('orderer_name', models.CharField(max_length=100, verbose_name='依頼者名')),
                ('has_changes', models.BooleanField(default=False, verbose_name='変更点の有無')),
                ('note', models.TextField(blank=True, verbose_name='備考・変更点')),
                ('price_at_order', models.IntegerField(default=0, verbose_name='注文時価格')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='顧客')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.product', verbose_name='商品')),
            ],
        ),
    ]
